#!/bin/sh

start() {
	echo "my script start!!!!!"
	bash /etc/init.d/scripts.sh
}

stop() {
	echo "my script stop!!!!!"
}

restart() {
	echo "my script restart!!!!!"
	bash /etc/init.d/scripts.sh
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
        stop
        start
        ;;
	*)
		echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

